apiVersion: v1
kind: Service
metadata:
  name: argo-demo-service
  labels:
    app: argo-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: argo-demo
---
apiVersion: v1
kind: Service
metadata:
  name: argo-demo-nodeport
  labels:
    app: argo-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: argo-demo