name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./argo-workflow-demo
        file: ./argo-workflow-demo/Dockerfile
        push: true
        tags: |
          fengyuxiu/argo-demo:latest
          fengyuxiu/argo-demo:${{ github.sha }}

    - name: Update Kubernetes manifests with new image
      if: github.event_name == 'push'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        sed -i "s|image: fengyuxiu/argo-demo:.*|image: fengyuxiu/argo-demo:${{ github.sha }}|" ./deploy/deploy.yaml

        git add ./deploy/deploy.yaml
        git commit -m "Update image to fengyuxiu/argo-demo:${{ github.sha }}" || echo "No changes to commit"
        git push
